version: '3.8'

services:
  chroma:
    image: chromadb/chroma
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8000:8000"

  app:
    build: .
    depends_on:
      - chroma
    ports:
      - "3000:3000"
    volumes:
      - ./code-to-analyze:/app/code-to-analyze
      - chroma-data:/app/chroma-db
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000

volumes:
  chroma-data: